### ISSUE TITLE
Add an option to override the Ion id in `submitExternalPing` (mozilla-central)

### ISSUE THREAD

**Issue by Dexterp37** [mozilla-ion/ion-core-addon#100]
With the new architecture the Ion id is stored in the Core addon. Unfortunately this means that `TelemetryController.submitExternalPing` [will throw](https://searchfox.org/mozilla-central/rev/61728de8273c04fe2417c475fc0637e8b79210d7/toolkit/components/telemetry/app/TelemetryControllerParent.jsm#492-498) unless it is also set in the `toolkit.telemetry.pioneerId` pref.

To keep both `about:ion` and Ion Core working when it comes to telemetry, we will need to add an `overridePioneerId` option (like [`overrideClientId`](https://searchfox.org/mozilla-central/rev/61728de8273c04fe2417c475fc0637e8b79210d7/toolkit/components/telemetry/app/TelemetryControllerParent.jsm#441-442)) that, if present, will use the provided id and no check the pref at all.

**Comment by marniepw** [comment]
I believe this will need to ride the trains, based on conversation.

**Comment by Dexterp37** [comment]
I filed [this bugzilla bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1673554) to track the m-c work.
