### ISSUE TITLE
Add public/fonts/** to .gitignore?

### ISSUE THREAD

**Issue by pdehaan** [mozilla-ion/ion-core-addon#120]
Looks like the rollup.config.js file is copying over some font assets to ./public/fonts/ which then get staged after running <kbd>npm run build</kbd>. Not sure if we want to add that path to .gitignore so we don't check in the fonts accidentally (since they're already being copied via rollup and the `@mozilla-protocol` module).

https://github.com/mozilla-ion/ion-core-addon/blob/ce96118e92b988fc18b3f416c17f1284f34d181b/rollup.config.js#L55-L59

**Comment by Dexterp37** [comment]
Yes, I believe this is a good idea. @hamilton , what's your take on it?

**Comment by hamilton** [comment]
That's a great idea @pdehaan – always happy to prevent accidental check-ins.
