### ISSUE TITLE
assert.equal() is deprecated

### ISSUE THREAD

**Issue by pdehaan** [mozilla-ion/ion-core-addon#121]
Per, [Node API docs](https://nodejs.org/api/assert.html#assert_assert_equal_actual_expected_message) `assert.equal()` is deprecated since v9.9.0 &mdash; use `strictEqual()` instead.

```js
/** @deprecated since v9.9.0 - use strictEqual() instead. */
function equal(actual: any, expected: any, message?: string | Error): void;
```

Trying to find an ESLint config that can flag deprecated Node APIs for us. Early research shows https://github.com/mysticatea/eslint-plugin-node should do the trick, but I need to figure out how to configure it and silence some of the noisier recommended rules.

**Comment by pdehaan** [comment]
https://github.com/mysticatea/eslint-plugin-node/issues/219

**Comment by pdehaan** [comment]
Easiest solution might be to just set **assert**'s `strict` mode when requiring the **assert** module:

```js
var assert = require('assert').strict;
```

It looks like after enabling strict mode, one of the tests failed because of an odd `null` => `undefined` cast when not in strict mode:

```diff
git diff tests/core-addon/IonCore.test.js 

diff --git a/tests/core-addon/IonCore.test.js b/tests/core-addon/IonCore.test.js
index 0ab814c..ebdcaf3 100644
--- a/tests/core-addon/IonCore.test.js
+++ b/tests/core-addon/IonCore.test.js
@@ -2,7 +2,7 @@
  * License, v. 2.0. If a copy of the MPL was not distributed with this
  * file, You can obtain one at http://mozilla.org/MPL/2.0/. */
 
-var assert = require('assert');
+var assert = require('assert').strict;
 var sinon = require('sinon');
 
 var IonCore = require('../../core-addon/IonCore');
@@ -427,7 +427,7 @@ describe('IonCore', function () {
   describe('_updateInstalledStudies()', function () {
     it('adds the ionInstalled property', async function () {
       // We don't expect any update task to be running now.
-      assert.equal(this.ionCore._updateInstalledTask, null);
+      assert.equal(this.ionCore._updateInstalledTask, undefined);
       // Kick off an update task.
       let studies =
         await this.ionCore._updateInstalledStudies(FAKE_STUDY_LIST);
```

I can PR this shortly, but doesn't look like the **eslint-plugin-node**'s `no-deprecated-api` flags this API, but 🤷 .

**Comment by Dexterp37** [comment]
> It looks like after enabling strict mode, one of the tests failed because of an odd `null` => `undefined` cast when not in strict mode:

And that flagged a real problem :) I left a comment on the PR. Thanks for doing this!
