### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by rhelmer** [mozilla-ion/ion-core-addon#16]
We need basic CI to run tests, it should cause tests to run in both Firefox and Chrome. The Chrome experience does not need to be fully fleshed out, but we want to catch basic compatibility problems early.

**Comment by Dexterp37** [comment]
I see us having to have at least a few tasks:

- code linting (eslint?)
- unit tests (mocha)
- integration tests (Firefox headless?)

What do you think?

**Comment by rhelmer** [comment]
> I see us having to have at least a few tasks:
> 
>     1. code linting (eslint?)
> 
>     2. unit tests (mocha)
> 
>     3. integration tests (Firefox headless?)
> 
> 
> (1) and (2) sound like low hanging fruits and can be easily done on circleCi. (3) might be more complicated What do you think?

I agree, (3) is the hard one. There are some examples of this such as https://github.com/mdn/webextensions-examples/tree/master/mocha-client-tests and https://www.npmjs.com/package/sinon-chrome that we need to evaluate.

**Comment by rhelmer** [comment]
Since @hamilton and I decided to keep the website in this repo as well, we'll want a way to run tests for and publish the website also.

**Comment by hamilton** [comment]
Would it make sense to split this so we can focus on getting (1) and (2) for this checkpoint, with an eye toward (3) for the next? This will enable more tests to be written & PRs to be easier to accept.

**Comment by rhelmer** [comment]
> Would it make sense to split this so we can focus on getting (1) and (2) for this checkpoint, with an eye toward (3) for the next? This will enable more tests to be written & PRs to be easier to accept.

Yes there is no reason not to get going on this - do you have an opinion on which CI we should use? I think Circle was mentioned before, how can we get that going?

**Comment by Dexterp37** [comment]
> 
> 
> > Would it make sense to split this so we can focus on getting (1) and (2) for this checkpoint, with an eye toward (3) for the next? This will enable more tests to be written & PRs to be easier to accept.
> 
> Yes there is no reason not to get going on this - do you have an opinion on which CI we should use? I think Circle was mentioned before, how can we get that going?

We have prior art for this in our Glean team, I'm happy to tackle the CircleCI setup for (1) and (2)!

> I agree, (3) is the hard one. There are some examples of this such as https://github.com/mdn/webextensions-examples/tree/master/mocha-client-tests and https://www.npmjs.com/package/sinon-chrome that we need to evaluate.

Note that we're already using "sinon-chrome" for the unit tests :-)

**Comment by Dexterp37** [comment]
Note: this is currently blocked on the fact that the mozilla-ion org requires some more setup. @knowtheory is working on that.

**Comment by Dexterp37** [comment]
All right, CI is now running on commits to master, see https://app.circleci.com/pipelines/github/mozilla-ion . I added the checks for unit tests and linting. I filed #55 for the integration tests.
