### ISSUE TITLE
Investigate Integration Testing

### ISSUE THREAD

**Issue by marniepw** [mozilla-ion/ion-core-addon#161]
Minimal integration testing investigation.

**Comment by marniepw** [comment]
Scope with @Dexterp37 and @rhelmer to see if a contractor can do this. Create a test plan so contractor can do this.

**Comment by rhelmer** [comment]
@marniepw I think this is a browser automation sort of task, anyone with Selenium/Webdriver experience or even puppeteer/playwright should be able to understand what we're trying to do.

**Comment by Dexterp37** [comment]
This can be closed. @rhelmer merged #212 .
