### ISSUE TITLE
Name Checkpoint 6

### ISSUE THREAD

**Issue by marniepw** [mozilla-ion/ion-core-addon#175]
Roy, please wear an amazing t-shirt so we can figure out what to name this Checkpoint.

**Comment by javaun** [comment]
Point of parliamentary procedure: should we in the future become blocked/constrained on laundry, I propose that we could allow Roy to extend naming to things like interesting food combinations, or things he pulls off Ted's desk

**Comment by marniepw** [comment]
Decided 12/4, 11:30am PT, based on Roy's onesie.
