### ISSUE TITLE
Deploy the schema for the `demographic-survey` ping

### ISSUE THREAD

**Issue by Dexterp37** [mozilla-ion/ion-core-addon#182]
With #139 , we will start sending encrypted pings to our pipeline. However, they will be thrown away until we deploy a schema for them.

It doesn't make sense to deploy one until we know the final shape of the data we'll send. And that's blocked on #169.

**Comment by Dexterp37** [comment]
As @acmiyaguchi suggested, we should also remove the previously deployed `survey` and `probes` schemas which are now unused.

**Comment by acmiyaguchi** [comment]
The schema can be added with the placeholder schemas, which is an empty schema that will route all of the data into the `additional_properties` field. This way the data won't be rejected and can be inspected using BigQuery json udfs.

**Comment by Dexterp37** [comment]
The PR: https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/647

**Comment by Dexterp37** [comment]
The schema was merged. Will be deployed in the next few days.
