### ISSUE TITLE
Should we provide a "kill switch" to remove a bad study?

### ISSUE THREAD

**Issue by hamilton** [mozilla-ion/ion-core-addon#189]
This came up in a discussion with @rhelmer. I am assuming that we probably won't get to this until after GTM, but filing now for coverage.

**Comment by jcchuang** [comment]
Or a pause-and-resume switch -- in case a study is broken, leaking PII and/or disrupting user browsing experience -- so that we can immediately stop all potential damages, fix the issues, before the study can continue.

**Comment by rhelmer** [comment]
We did decide to do this and I am working on a proposal in https://github.com/mozilla-ion/ion-core-addon/issues/132



> Or a pause-and-resume switch -- in case a study is broken, leaking PII and/or disrupting user browsing experience -- so that we can immediately stop all potential damages, fix the issues, before the study can continue.

I'll make sure "pause" and "resume" is part of it :) I think that's what folks mean with "kill switch" but let's be explicit.
