### ISSUE TITLE
release version 2.3 of the core add-on

### ISSUE THREAD

**Issue by rhelmer** [mozilla-ion/ion-core-addon#195]
Let's cut a new release on github, and set it up on https://mozilla-ion.github.io/ion-core-addon/

We can put the dev-signed build up for now, and also use this issue to track getting it prod-signed.

**Comment by rhelmer** [comment]
Release is done https://github.com/mozilla-ion/ion-core-addon/releases/tag/v2.2 - I am leaving this issue open to track the following:

- [ ] post dev-signed XPI to the above release
- [ ] point https://mozilla-ion.github.io/ion-core-addon/ at dev-signed add-on
- [ ] get a production-signed XPI from AMO admins and update release + https://mozilla-ion.github.io/ion-core-addon/

**Comment by rhelmer** [comment]
Actually I think we should do a 2.2.1 to include `mozilla-recommendation.json` per https://github.com/mozilla-ion/ion-core-addon/issues/159#issuecomment-731624422 so we get "badging" and more importantly suppresses the warning prompt when installing from a non-AMO origin.

**Comment by Dexterp37** [comment]
@rhelmer can we release the core addon with a pre-1.0 version? It seems a bit weird to be at version 2 when 1 was never out :E

**Comment by rhelmer** [comment]
This is taking long enough that we're on 2.3 https://github.com/mozilla-ion/ion-core-addon/releases/tag/v2.3

> @rhelmer can we release the core addon with a pre-1.0 version? It seems a bit weird to be at version 2 when 1 was never out :E

I'm not sure why we started with 2.0 :) @Dexterp37 would you mind filing an issue? Since it's pre-release I suggest we clean up the existing tags and reset to 0.23

**Comment by hamilton** [comment]
Closing this one for now, and @rhelmer is going to open an issue for 0.6
