### ISSUE TITLE
The Core Add-On needs to be able to detect that a study add-on is installed

### ISSUE THREAD

**Issue by hamilton** [mozilla-ion/ion-core-addon#20]
This was a note from the engineering checkpoints doc. I believe this was considered the bare-minimum for our current checkpoint.

**Comment by Dexterp37** [comment]
I propose the following:

1. once the Core Addon starts, thanks to #39 it fetches the list of available studies (and their ids);
2. once the list is available, Core Addon enumerates all the installed addons.
3. if any of the installed addon is present in the fetched study list (available studies), mark them as installed.
4. report the installed studies to the UI.

@hamilton @rhelmer does the above make sense? If it does, how should we handle (4)?

**Comment by hamilton** [comment]
The installed studies should appear in the UI (for now) if the addon id is in the `activeStudies` key-value pair (the value is an array of study ids). We can change this in the future, but that's how it works now. To make sure the study id is present when the UI opens, we'll need to add something to the `initialize` function in `web-extension.js` that fetches the studies. We could probably also put the `getAvailableStudies` call in `initialize` as well but I can do that later.

**Comment by rhelmer** [comment]
Instead of having to rely on message-passing for everything, I think we can use the `getAll()` management API to get the list of available add-ons that are installed: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/management

Note that Firefox does not support all these APIs, and there are no plans to implement the `install` and `uninstall` ones unfortunately due to security concerns, although Chrome does have support.

Luca (@rpl) thinks that the `onInstalled/uninstalled/enabled/disabled` listeners might actually be implemented and the compat data on MDN might be out of date there so we should test this. If these do indeed work, this would be a very easy way to keep the UI up-to-date.

**Comment by rhelmer** [comment]
We would therefore still rely on message-passing to tell add-ons to uninstall themselves, and also (potentially) to pass messages for Telemetry which would allow us to keep the study add-on unprivileged. Issue #43 covers this decision.

Using the webextension `management` API this would alleviate many of the concerns I have around getting message-passing, if we're able to restrict the needs to just the above.

**Comment by rhelmer** [comment]
> Luca (@rpl) thinks that the `onInstalled/uninstalled/enabled/disabled` listeners might actually be implemented and the compat data on MDN might be out of date there so we should test this. If these do indeed work, this would be a very easy way to keep the UI up-to-date.

I did a quick test using the devtools and this seems to work! Looks like we can listen for enabled/disabled as well as installed/uninstalled, and keep the core add-on in-sync this way.

**Comment by Dexterp37** [comment]
> 
> 
> Instead of having to rely on message-passing for everything, I think we can use the `getAll()` management API to get the list of available add-ons that are installed: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/management

Yes, this is exactly what I had in mind for step (2) in my initial comment ;-)

> Note that Firefox does not support all these APIs, and there are no plans to implement the `install` and `uninstall` ones unfortunately due to security concerns, although Chrome does have support.
> 
> Luca (@rpl) thinks that the `onInstalled/uninstalled/enabled/disabled` listeners might actually be implemented and the compat data on MDN might be out of date there so we should test this. If these do indeed work, this would be a very easy way to keep the UI up-to-date.

I'm fairly sure `onInstalled` works because we're already using it to show the initial page of the Core Addon as soon as it is installed!
