### ISSUE TITLE
If a user manually uninstalls a study through the addon manager, does it fire a deletion ping?

### ISSUE THREAD

**Issue by knowtheory** [mozilla-ion/ion-core-addon#203]
This is a reminder for me to find out what the current behavior is.

**Comment by Dexterp37** [comment]
@knowtheory yes, it does fire a deletion request. The Core addon keeps track of study installation/uninstallation even outside of the control panel. [See the current implementation](https://github.com/mozilla-ion/ion-core-addon/blob/2ddb3f82e27291d6ed1a8764b3b6ac6a801b1fce/core-addon/IonCore.js#L60-L64):

**Comment by knowtheory** [comment]
Awesome!  Thanks 👍
