### ISSUE TITLE
in the GTM flow, what is the expected outcome if a user leaves Rally?

### ISSUE THREAD

**Issue by hamilton** [mozilla-ion/ion-core-addon#205]
Realizing we don't quite have the answer to this question right now. When I click on this button

![Screen Shot 2020-11-30 at 1 41 59 PM](https://user-images.githubusercontent.com/95735/100669183-e1c24d00-3311-11eb-8142-85957c9e6597.png)

And consent, it's not clear what _exactly_ should happen for the user. Since we're pretty close to having the entire GTM experience in the Core Add-On itself, we should probably figure out precisely what the user will see.

I imagine it will look like:
1. remove all existing study add-ons (we do this already when a user leaves rally)
2. send deletion pings (already doing this as well)
3. close any currently-existing extension URLs
4. uninstall the core add-on

Does this seem reasonable?

**Comment by changecourse** [comment]
I agree, though I would posit that the confirmation overlay this link invokes would specify all 4 tasks you have called out to make it very clear to a user what is about to happen, prior to it occurring.

**Comment by hamilton** [comment]
we can use #147 to track the copy changes. Ryan has a shot of the treatment there.

**Comment by Dexterp37** [comment]
> I imagine it will look like:
> ...
>     3. close any currently-existing extension URLs
> 
>     4. uninstall the core add-on

(3) happens automatically if (4) is done.

However, why would we want to remove the addon? What if user wants to enroll again? if we leave the addon around, then we have one "less gate" to acquisition. If we remove it, then we go through the whole re-enrollment again.

I have no strong opinion though, let's just think carefully :)

**Comment by hamilton** [comment]
@Dexterp37 Totally agreed. On slack, Javaun notes that we may actually be legally required to remove the add-on. I'll follow up with him to be sure we're doing the right thing.

**Comment by changecourse** [comment]
@Dexterp37 there may be legal requirements for us to need to remove (regardless of user expectation) the add-on, according to @javaun 

Furthermore, if we do a nice website redirect to a "sorry to see you go" type message (logged in #206) we can properly reroute folks back in as necessary.

**Comment by javaun** [comment]
Here were the prior requirements for About Pioneer. The "leaving" cleanup was all study add-ons, any browser state (prefs, etc) that would allow the user to be counted/targeted, plus the "core add on" itself (which at that time was envisioned to include telemetry and/or browsing data). https://docs.google.com/spreadsheets/d/1-a-5iLNQk0aUyEA6XdHgYDbT94-R93iRg6-kqmwdkKE/edit#gid=0

Let's look at this from two sides though: user expectation and legal responsibilities. 
We are suppressing some prompts on enrollment, or at the very least deviating from the traditional add-on experience to make this feel as seamless as possible. In the absence of other user evidence, I would assert the expectation is that leaving means leaving and we need to delete the core addon and revert any other browser state (if we've modified it) that would allow the user to be targeted or counted as a Rally user. We also have a rather unnuanced approach to data collection in that it is tied to enrollment -- if you're enrolled (in Rally and /or studies) we collect data. We don't offer granular data controls. To turn off a study's data collection, you leave the study.  I think we should treat Rally the same and delete Add-on on leaving, even if it means re-enrollment friction. That also argues for a confirmation on leaving, not to change user's minds, but to make sure that they understand what leaving means.

Re: legal. I went back through our privacy notices and didn't see specific verbiage. Originally we'd envisioned doing cat 3/4 data collection in the core add-on. With where we are now it's probably gray area and we could investigate. I think the compelling reason to delete the core add-on is user expectation. We can ask Ryan here. I believe our current UX would set the expectation that leaving deletes everything, and we'd have to overcome that to keep the core add-on

**Comment by changecourse** [comment]
It sounds like we're all in generally in agreement to uninstall/delete everything (recognizing that there's future friction for rejoining @Dexterp37, but acknowledging that it's likely better to meet likely user expectation and reinforcing it with the content in #206)

**Comment by Dexterp37** [comment]
> 
> 
> It sounds like we're all in generally in agreement to uninstall/delete everything (recognizing that there's future friction for rejoining @Dexterp37, but acknowledging that it's likely better to meet likely user expectation and reinforcing it with the content in #206)

Lovely! Great conversation folks, uninstall it is!

**Comment by hamilton** [comment]
Glad this got resolved. Closing in favor of the engineering-focused #207
