### ISSUE TITLE
remove reliance on Pioneer ID pref

### ISSUE THREAD

**Issue by rhelmer** [mozilla-ion/ion-core-addon#237]
The Core Add-on is still using the Pioneer ID pref in Firefox, @Dexterp37 does https://bugzilla.mozilla.org/show_bug.cgi?id=1673554 let us move away from this?

See also issue #236 (turned out to be a different problem but reminded me that we probably don't need to use this pref anymore!)

**Comment by Dexterp37** [comment]
> 
> 
> The Core Add-on is still using the Pioneer ID pref in Firefox, @Dexterp37 does https://bugzilla.mozilla.org/show_bug.cgi?id=1673554 let us move away from this?

Only if we exclusively want to target 84 upwards! So this is more of a product question. @hamilton @knowtheory @javaun ?

**Comment by rhelmer** [comment]
> > The Core Add-on is still using the Pioneer ID pref in Firefox, @Dexterp37 does https://bugzilla.mozilla.org/show_bug.cgi?id=1673554 let us move away from this?
> 
> Only if we exclusively want to target 84 upwards! So this is more of a product question. @hamilton @knowtheory @javaun ?

Isn't there a problem with trying to support <84 though, if you flip this pref on or off it'll affect the built-in Ion (enable the built-in icon and data collection?) We'd need to ship privileged code in the core add-on to support older Firefoxes at this point I think.

**Comment by Dexterp37** [comment]
> 
> 
> > > The Core Add-on is still using the Pioneer ID pref in Firefox, @Dexterp37 does https://bugzilla.mozilla.org/show_bug.cgi?id=1673554 let us move away from this?
> > 
> > 
> > Only if we exclusively want to target 84 upwards! So this is more of a product question. @hamilton @knowtheory @javaun ?
> 
> Isn't there a problem with trying to support <84 though, if you flip this pref on or off it'll affect the built-in Ion (enable the built-in icon and data collection?) We'd need to ship privileged code in the core add-on to support older Firefoxes at this point I think.

Good point. Let me remove support for this pref, we can deal with migration and old version in #25
