### ISSUE TITLE
should the demo study be privileged right now?

### ISSUE THREAD

**Issue by hamilton** [mozilla-ion/ion-core-addon#43]
This is primarily for a demo experience. We'd like to have the demo add on installable as a end-to-end demo.

pros:
- can easily send its own telemetry if privileged
cons:
- will have to sign this, which will add overhead

cc @Dexterp37

**Comment by rhelmer** [comment]
One advantage to having it be unprivileged is that we can use the normal AMO mechanism, which tends to be very quick. It gives us an easy place to host updates too.

I've had AMO reviewers be grumpy about my uploading "demo" add-ons and things, but we can navigate that. We're going to need to for study add-ons generally as we move towards store hosting.

**Comment by rhelmer** [comment]
Note that we can *also* do privileged signing and also host on AMO, it just takes longer (extra steps and manual approvals)

**Comment by Dexterp37** [comment]
> 
> 
> One advantage to having it be unprivileged is that we can use the normal AMO signing mechanism, which tends to be very quick. It gives us an easy place to host updates too.
> 
> I've had AMO reviewers be grumpy about my uploading "demo" add-ons and things, but we can navigate that. We're going to need to for study add-ons generally as we move towards store hosting.

I agree with the above statements, and I don't think we should test/evaluate privileged studies at this time. They are an exception, and we should really prototype the "common case" (unprivileged studies).

**Comment by rhelmer** [comment]
OK I'm going to remove the privileged code in https://github.com/mozilla-ion/demo-study-addon/issues/3 as we'll need to figure out the message-passing for Telemetry to make it actually work.
