### ISSUE TITLE
remove all UX state management from the frontend store and use the background persistent store as the source of truth

### ISSUE THREAD

**Issue by hamilton** [mozilla-ion/ion-core-addon#46]
To get the UX bootstrapped, I initially put together the UX state management in the frontend to demonstrate the experience. This wasn't really meant to be a long-term solution. It would be substantially easier if we moved the state management out of the frontend portion entirely and handled state changes, reconciliation, and synchronization away from the UX. This means that the UX store will simply be a reflection of what's in the add-on persistent storage.

The frontend should have two API endpoints: `sendToCore` and `onNextState`. The former should be used to send messages to the background, kind of like redux actions. _We already have `sendToCore` today_. `onNextState` should be used to simply replace the state entirely on the frontend. The callback argument is just a new state, and the frontend can just call `store.set` on that to completely replace the state on each relevant store update. The goal is to follow the traditional state management approach everyone uses: store updates always return an entirely new copy of the store, and the frontend framework consumes that & determines what needs to update reactively as a result.

The background will have the same kinds of endpoints: `sendToAll` and `onMessage`. I think @Dexterp37 has already implemented some kind of `onMessage` through `_handleMessage` in `IonCore.js`. We can make sure that the `sendToAll` functionality happens through connection-based message passing, so that the frontend's `onNextState` will get the reconciled UX state when the background updates.

Taking this approach has a few advantages:

1. if I have two extension URLs opened, they'll always be synchronized, since they both receive messages from the background about the reconciled state.
2. if, for instance, a study add-on gets uninstalled outside of the normal core add-on UX flow, the new state can easily be pushed to any extension URLs opened.
3. we're preparing for any amount of future complexity by reducing the code footprint on the frontend. The work should only be done in one place.

fwiw we did this in Iodide (similar situation where there was a lot of message passing) and it drastically improved maintainability.

cc @Dexterp37 @rhelmer

**Comment by Dexterp37** [comment]
> The background will have the same kinds of endpoints: `sendToAll` and `onMessage`. I think @Dexterp37 has already implemented some kind of `onMessage` through `_handleMessage` in `IonCore.js`. We can make sure that the `sendToAll` functionality happens through connection-based message passing, so that the frontend's `onNextState` will get the reconciled UX state when the background updates.

The `sendToAll` part is for sending messages to all the opened extension pages?

> Taking this approach has a few advantages:
> 
>     1. if I have two extension URLs opened, they'll always be synchronized, since they both receive messages from the background about the reconciled state.

@rhelmer do you know if we can have more than one options page open (the current page is opened as an options page)?

**Comment by hamilton** [comment]
> The sendToAll part is for sending messages to all the opened extension pages?

I think so, via [tabs.sendMessage](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/sendMessage).

**Comment by Dexterp37** [comment]
This was done by #97
