### ISSUE TITLE
implement message-passing from study to core for Telemetry

### ISSUE THREAD

**Issue by rhelmer** [mozilla-ion/ion-core-addon#47]
We need to pass [telemetry from the unprivileged add-on](https://github.com/mozilla-ion/ion-basic-study/pull/4#discussion_r504109099) to the Ion Core add-on.

We'll also need to figure out how to pass [the public key](https://github.com/mozilla-ion/ion-basic-study/pull/4#discussion_r504109549) from the study add-on, ideally not along with every single message :)

**Comment by Dexterp37** [comment]
> We'll also need to figure out how to pass [the public key](https://github.com/mozilla-ion/ion-basic-study/pull/4#discussion_r504109549) from the study add-on, ideally not along with every single message :)

I'll think this piece through! But do we suspect passing the key to become a bottleneck? I don't expect telemetry pings to be super frequent. I'd recommend doing the simple thing now (passing the info along) and then adjust when this becomes a problem.

@rhelmer do you see a specific problem with passing the public key on a low frequency cadence?

**Comment by rhelmer** [comment]
> > We'll also need to figure out how to pass [the public key](https://github.com/mozilla-ion/ion-basic-study/pull/4#discussion_r504109549) from the study add-on, ideally not along with every single message :)
> 
> I'll think this piece through! But do we suspect passing the key to become a bottleneck? I don't expect telemetry pings to be super frequent. I'd recommend doing the simple thing now (passing the info along) and then adjust when this becomes a problem.

I hope so too :) I don't know how to quantify it though, to be able to tell study authors how often is too often. I'd like to know what the failure mode is (dropped messages, laggy browser/add-ons, etc)
 
> @rhelmer do you see a specific problem with passing the public key on a low frequency cadence?

This seems OK (we could even pass it once on startup I guess), although I've been curious to know if there's a way to establish long-lived connections versus one-off: https://developer.chrome.com/extensions/messaging#connect

It's not clear to me from that document if this works for add-ons though.

**Comment by Dexterp37** [comment]
> 
> 
> > > We'll also need to figure out how to pass [the public key](https://github.com/mozilla-ion/ion-basic-study/pull/4#discussion_r504109549) from the study add-on, ideally not along with every single message :)
> > 
> > 
> > I'll think this piece through! But do we suspect passing the key to become a bottleneck? I don't expect telemetry pings to be super frequent. I'd recommend doing the simple thing now (passing the info along) and then adjust when this becomes a problem.
> 
> I hope so too :) I don't know how to quantify it though, to be able to tell study authors how often is too often. I'd like to know what the failure mode is (dropped messages, laggy browser/add-ons, etc)

This is a kind of question to be answered at "data review time". In addition to the engineering constraint of flooding the message channel between addons, there's the "collection and analysis at scale" problem :-) Sending pings too frequently might create problems on other levels, too ;-)

Consider this: both legacy telemetry and glean throttle and allow uploading _at most_ 10 pings per minute (among *all* the pings being sent!). 

> > @rhelmer do you see a specific problem with passing the public key on a low frequency cadence?
> 
> This seems OK (we could even pass it once on startup I guess), although I've been curious to know if there's a way to establish long-lived connections versus one-off: https://developer.chrome.com/extensions/messaging#connect
> 
> It's not clear to me from that document if this works for add-ons though.

Yes, I investigate the connection-based pattern and we might want to migrate to that in the future!
