### ISSUE TITLE
Should we enforce linting rules?

### ISSUE THREAD

**Issue by hamilton** [mozilla-ion/ion-core-addon#59]
Would be great to use eslint to standardize this codebase & have it be part of our CI. This will remove the need for formatting comments from reviewers going forward & save us time.

**Comment by Dexterp37** [comment]
As of today, we already enforce linting of the addon code using `web-ext`. Do you mean linting for the website code?

**Comment by hamilton** [comment]
Yep, we should lint everything (including svelte files) and it should be enforceable at the editor level.

**Comment by Dexterp37** [comment]
There's some traction in #118, so let's close this.
