### ISSUE TITLE
wait for study add-on to be installed before saying a study is "active" in the store

### ISSUE THREAD

**Issue by hamilton** [mozilla-ion/ion-core-addon#60]
As of this filing, the UX around enrolling in a study is a little odd. The frontend should note that the study enrollment / add-on installation has finished only _after_ it has actually finished.

This will be much easier to fulfill after #46.

**Comment by Dexterp37** [comment]
Note that this is related to #81 .

**Comment by Dexterp37** [comment]
Closed by #97
