### ISSUE TITLE
Merge back build system changes from mozilla-extensions clone

### ISSUE THREAD

**Issue by rhelmer** [mozilla-ion/ion-core-addon#66]
I've made a mess of the build system in the mozilla-extensions clone (required for privileged signing), I need to clean that up and merge it back https://github.com/mozilla-extensions/ion-core-addon

Let's file bugs upstream also on the following issues:

- [ ] dep-signing task does not work for forks
- [ ] build target should be configurable
- [ ] determine the problem with the dev dependencies in our `package.json`

I believe that we need to merge https://github.com/mozilla-ion/ion-core-addon/pull/199 in order to get TC to start paying attention to this repo. We can further debug the latter two issues after that's merged.

**Comment by rhelmer** [comment]
Testing this in https://github.com/mozilla-extensions/ion-core-addon/pull/1 - since these are separate repos and not forks, one must fork the mozilla-extensions/ion-core-addon separately which is annoying but OK for now (we can't use a fork because there's a bug in addons-pipeline where dep-signed builds will not be produced)

**Comment by Dexterp37** [comment]
> 
> 
> Testing this in [mozilla-extensions/ion-core-addon#1](https://github.com/mozilla-extensions/ion-core-addon/pull/1) - since these are separate repos and not forks, one must fork the mozilla-extensions/ion-core-addon separately which is annoying but OK for now (we can't use a fork because there's a bug in addons-pipeline where dep-signed builds will not be produced)

Thanks for doing this! I have a few thoughts, but I think I'm missing something, so bear with me as I might be saying many wrong things in this comment :-)

mozilla-extensions/ion-core-addon#1 seems to be trying to merge from [your fork](https://github.com/rhelmer/ion-core-addon-1) to the fork in `mozilla-extensions`, which we require for signing. A few questions below:

* Can we treat the fork in `mozilla-extensions` as "read-only"? This means any chance that needs to happen will be required to happen in `mozilla-ion/ion-core-addon`. Once merged, we can open a PR directly in `mozilla-extensions/ion-core-addon` updating it to the latest `master` of our main repo. This should always be a fast-forward merge, with no conflicts. Ideally, this could be automated: if we cut a new release in this repo (through GitHub release tags), we could open that PR automatically and trigger any dependant signing job. How does that sound?
* Are we lacking any tweak that was made to `mozilla-extensions/ion-core-addon` and is not in `mozilla-ion/ion-core-addon`?

@rhelmer what do you think of the above?

**Comment by rhelmer** [comment]
> 
> 
> > Testing this in [mozilla-extensions/ion-core-addon#1](https://github.com/mozilla-extensions/ion-core-addon/pull/1) - since these are separate repos and not forks, one must fork the mozilla-extensions/ion-core-addon separately which is annoying but OK for now (we can't use a fork because there's a bug in addons-pipeline where dep-signed builds will not be produced)
> 
> Thanks for doing this! I have a few thoughts, but I think I'm missing something, so bear with me as I might be saying many wrong things in this comment :-)
> 
> [mozilla-extensions/ion-core-addon#1](https://github.com/mozilla-extensions/ion-core-addon/pull/1) seems to be trying to merge from [your fork](https://github.com/rhelmer/ion-core-addon-1) to the fork in `mozilla-extensions`, which we require for signing. A few questions below:
> 
>     * Can we treat the fork in `mozilla-extensions` as "read-only"? This means any chance that needs to happen will be required to happen in `mozilla-ion/ion-core-addon`. Once merged, we can open a PR directly in `mozilla-extensions/ion-core-addon` updating it to the latest `master` of our main repo. This should always be a fast-forward merge, with no conflicts. Ideally, this could be automated: if we cut a new release in this repo (through GitHub release tags), we could open that PR automatically and trigger any dependant signing job. How does that sound?
> 
>     * Are we lacking any tweak that was made to `mozilla-extensions/ion-core-addon` and is not in `mozilla-ion/ion-core-addon`?
> 
> 
> @rhelmer what do you think of the above?

Yes, I think that makes sense. The PR workflow would be better than the way I've been doing it :)

We may want to just force-push over the existing repo once we have things merged back so we have a cleaner starting point, there are a few tags that only exist in the `mozilla-extensions` clone that we can bring over.

**Comment by rhelmer** [comment]
To answer your second question, there are a couple tweaks we need to bring back to our upstream repo (which I intend to do in a PR here, I have a PR open in `mozilla-extensions/ion-core-addon` so that I can have the taskcluster CI run and make sure my changes are correct).

The workflow you're proposing would be easier to keep track of, I think.

**Comment by Dexterp37** [comment]
Cool! Let me know if there's anything I can do to help, @rhelmer !

**Comment by rhelmer** [comment]
OK I am confirming this with #addons-pipeline folks, but since we haven't done a release over there I am checking with them to see if I can just force-push over https://github.com/mozilla-extensions/ion-core-addon so we can get back on track and start using a PR workflow for this. I've been pushing to master over there and merging so it's a mess and doesn't need to be this way :)

**Comment by rhelmer** [comment]
Well, hmph. It seems like taskcluster only runs once per PR, I've tried both updating normally and ffwd-ing: https://github.com/mozilla-extensions/ion-core-addon/pull/2

I'll file a bug with the #addons-pipline folks, this is going to really cramp our style :)

**Comment by rhelmer** [comment]
Actually... I'm going to speculate that it's not running because there's no `taskcluster.yml` on the `master` branch, I remember when trying to use TC from GitHub that being an issue.

Assuming this is correct, it's coming up because I force-pushed `master` over the mozilla-extensions/ion-core-addon clone, I think it'd be safe to just land a `.taskcluster.yml` in our repo and push that over. I'll confirm with the folks in #addons-pipeline
