### ISSUE TITLE
create npm package in this repository or somewhere for ion.js

### ISSUE THREAD

**Issue by hamilton** [mozilla-ion/ion-core-addon#75]
This was a note from Checkpoint 2a. The Basic Study Add-On has `ion.js`, which should be abstracted into a package and published on npm for others to use.

**Comment by Dexterp37** [comment]
@knowtheory @javaun @hamilton NPM allows us to create an "org" under which to release/group the packages. Should we create a `mozilla-rally` org? Do we prefer a different name? (names can't be changed)

**Comment by rhelmer** [comment]
Can we close this one? I believe we're set up to use the `mozilla` org now.
