### ISSUE TITLE
where does demographic information live?

### ISSUE THREAD

**Issue by hamilton** [mozilla-ion/ion-core-addon#91]
Does it need to be sent back to the server?

**Comment by hamilton** [comment]
I think this was anwered – it needs to be submitted to the server and also persisted in the add-on storage.

**Comment by Dexterp37** [comment]
> 
> 
> I think this was anwered – it needs to be submitted to the server and also persisted in the add-on storage.

@hamilton I don't think this was completely answered: why do we need it persisted on storage?

**Comment by hamilton** [comment]
@dexterp37 to support potentially amending it in the future and re-submitting. There are open questions about _how_ we handle that from the partner side, but we want to perserve the option.

**Comment by Dexterp37** [comment]
> 
> 
> @Dexterp37 to support potentially amending it in the future and re-submitting. There are open questions about _how_ we handle that from the partner side, but we want to perserve the option.

Makes sense, thanks for explaining that!

> Sorry, I should have added that explanation before closing.

No worries, we're all running fast :-)
