### ISSUE TITLE
request QA resources

### ISSUE THREAD

**Issue by hamilton** [mozilla-ion/ion-core-addon#92]

**Comment by marniepw** [comment]
Expect to hear back from Krupa by the end of this week.

**Comment by hamilton** [comment]
We were denied the QA resources. Should we follow this up / move it to another checkpoint?

**Comment by marniepw** [comment]
It's possible I can still get QA for Firefox impacting work; it depends on getting the request in early enough (think: trains deadlines) and we get all the sundry "paperwork" filed in time.

**Comment by marniepw** [comment]
Alin Ilea seems to be open for QA-ing Firefox type work. I'll continue to work with him as needed.
